name: Deploy Portfolio

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar Astro
        run: npm run build

      - name: Publicar en Nginx
        run: |
          rm -rf /home/miguellugom97admin/servicios/portfolio/*
          cp -r dist/* /home/miguellugom97admin/servicios/portfolio/
